version: 2.1
workflows:
  test-deploy:
    jobs:
      - test
      - greet
commands:
  greet:
    description: "Hello sample command"
    steps:
      - run: echo "Hello sample command"
executors:
  test-executor:
      docker:
      - image: cimg/base:2024.01
jobs:
  test:
    executor: test-executor
    steps:
      - checkout
      - run:
          name: "check the test repo"
          command: echo "test repo"
      - run: pwd
      - run: ls -al
  # build:
  #   executor: test-executor
  #   steps:
  #     - checkout
  #     - run:
  #         name: "check teh test repo2 "
  #         command: echo "test repo is working"
