# version: 2.1
# workflows:
#   version: 2
#   test-deploy:
#     jobs:
#       - test
#   schedule-deploy:
#     triggers:
#       - schedule:
#           cron: "45 14 * * *"
#           filters:
#             branches:
#               only:
#                 - master
#     jobs:
#       - deploy

# executors:
#   test-executor:
#       docker:
#       - image: cimg/base:2024.01
# jobs:
#   test:
#     executor: test-executor
#     steps:
#       - checkout
#       - run:
#           name: "check the test repo"
#           command: echo "test repo"
#       - run: pwd
#       - run: ls -al
#   deploy:
#     executor: test-executor
#     steps:
#       - checkout
#       - run:
#           name: "run this job on a schedule time"
#           command: echo "This Job will run on a schedule time"
    
version: 2.1

executors:
  test-executor:
    docker:
      - image: circleci/node

jobs:
  test:
    executor: test-executor
    steps:
      - checkout
      - run:
          name: "check the test repo"
          command: echo "test repo"
      - run: pwd
      - run: ls -al

  deploy:
    executor: test-executor
    steps:
      - checkout
      - run:
          name: "run this job on a schedule time"
          command: echo "This Job will run on a schedule time"
workflows:
  version: 2
  test-deploy:
    jobs:
      - test
  schedule-deploy:
    triggers:
      - schedule:
          cron: "57 14 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test
      - deploy