version: 2.1

# workflows:
#   test-deploy:
#     jobs:
#       - test
jobs:
  test:
    docker:
      - image: cimg/node:21.6.1
    steps:
      - checkout
      - run:
          name: "check the test repo"
          command: echo "test repo"
      - run:
          name: "check the test 2"
          command: echo "test sample 2"
      - run: node --version

  # commands:
  #   sayhello:
  #     description: "A very simple command for demonstration purposes"
  #     parameters:
  #       to:
  #         type: string
  #         default: "Hello World"
  #     steps:
  #       - run: echo << parameters.to >>