version: 2.1

jobs:
  test:
    docker:
      - image: cimg/base:2024.01
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "check the test repo"
          command: echo "test repo"
      - run: pwd
  build:
    docker:
      - image: cimg/base:2024.01
    working_directory: ~/project
    steps:
      - checkout
      - run: whoami
      - run:
          name: "run this job on a schedule time"
          command: echo "This Job will run on a schedule time"
workflows:
  test-deploy:
    jobs:
      - test
  schedule-deploy:
    triggers:
      - schedule:
          cron: "43 15 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test
      - build