version: 2.1

workflows:
  test-deploy:
    jobs:
      - test
jobs:
  build:
    docker:
      - image: cimg/node:21.6.1
    steps:
      - checkout
      - run:
          name: "check the test repo"
          command: node --version