version: 2.1

workflows:
  test-deploy:
    jobs:
      - test
executors:
  test-executor:
      docker:
      - image: cimg/base:2024.01
jobs:
  test:
    executor: test-executor
    steps:
      - checkout
      - run:
          name: "check the test repo"
          command: echo "test repo"
  build:
    executor: test-executor
    steps:
      - checkout
      - run:
          name: "check teh test repo2 "
          command: echo "test repo is working"
