version: 2

jobs:
  build:
    machine: 
      image: ubuntu-2004:2023.10.1
    resource_class: arm.medium
    steps:
      - checkout
      - run: lscpu
  test:
    docker:
      - image: cimg/base:2024.01
    steps:
      - checkout
      - run:
          name: "check the test repo"
          command: echo "test repo"
      - run: pwd

  # build:
  #   docker:
  #     - image: cimg/base:2024.01
  #   steps:
  #     - checkout
  #     - run: whoami
  #     - run:
  #         name: "run this job on a schedule time"
  #         command: echo "This Job will run on a schedule time"
  # deploy:
  #   docker:
  #     - image: cimg/base:2024.01
  #   steps:
  #     - checkout
  #     - run: lscpu

workflows:
  version: 2
  test-workflow:
    jobs:
      - build
      - test



